#!/usr/bin/env bash
NAME="seedms"
VERSION="0.1.0"
DESCRIPTION="seedmsDescription"
CANONICAL_NAME="seedmsv01"
CONF_DIR="/etc/seedms"
CONF_FILE="/etc/seedms/seedmsv01.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/seedmsv01"
UNIT_NAME="seedmsv01.service"
UNIT_FILE="/etc/systemd/system/seedmsv01.service"
DOCS_DIR="/etc/seedms/docs"
