#!/usr/bin/env bash
NAME="seedms"
VERSION="0.1.0"
DESCRIPTION="Seed Micro-Service"
CANONICAL_NAME="seedmsv0"
CONF_DIR="/etc/seedms"
CONF_FILE="/etc/seedms/seedmsv0.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/seedmsv0"
UNIT_NAME="seedmsv0.service"
UNIT_FILE="/etc/systemd/system/seedmsv0.service"
DOCS_DIR="/etc/seedms/docs"
