// Code generated by protoc-gen-go.
// source: server/proto/seed.proto
// DO NOT EDIT!

/*
Package seed is a generated protocol buffer package.

It is generated from these files:
	server/proto/seed.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package seed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloResponse struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code     int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Greeting string `protobuf:"bytes,3,opt,name=greeting" json:"greeting,omitempty"`
	Detail   string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Seed service

type SeedClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type seedClient struct {
	c           client.Client
	serviceName string
}

func NewSeedClient(serviceName string, c client.Client) SeedClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "seed"
	}
	return &seedClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *seedClient) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Seed.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seed service

type SeedHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterSeedHandler(s server.Server, hdlr SeedHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Seed{hdlr}, opts...))
}

type Seed struct {
	SeedHandler
}

func (h *Seed) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.SeedHandler.Hello(ctx, in, out)
}

func init() { proto.RegisterFile("server/proto/seed.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0xae, 0x82, 0x30,
	0x10, 0x45, 0x1f, 0x3c, 0x20, 0x3a, 0x11, 0x16, 0x13, 0xa3, 0x0d, 0x2b, 0xc3, 0x8a, 0x15, 0x18,
	0xdd, 0xf8, 0x09, 0xae, 0xf1, 0x0b, 0xd0, 0x4e, 0x48, 0x23, 0xb6, 0xd8, 0x56, 0xbf, 0xdf, 0x38,
	0x10, 0xa3, 0xbb, 0x7b, 0xda, 0x39, 0x99, 0x3b, 0xb0, 0x76, 0x64, 0x9f, 0x64, 0xeb, 0xc1, 0x1a,
	0x6f, 0x6a, 0x47, 0x24, 0x2b, 0x8e, 0xc5, 0x01, 0x16, 0x47, 0xea, 0x7b, 0xd3, 0xd0, 0xfd, 0x41,
	0xce, 0xe3, 0x12, 0x62, 0x6f, 0xae, 0xa4, 0x45, 0xb0, 0x09, 0xca, 0x79, 0x33, 0x02, 0x22, 0x44,
	0xba, 0xbd, 0x91, 0x08, 0xf9, 0x91, 0x73, 0xd1, 0x41, 0x3a, 0x99, 0x6e, 0x30, 0xda, 0x11, 0x66,
	0x10, 0x2a, 0x39, 0x79, 0xa1, 0x92, 0x6f, 0xe9, 0x62, 0xe4, 0x28, 0xc5, 0x0d, 0x67, 0xcc, 0x61,
	0xd6, 0x59, 0x22, 0xaf, 0x74, 0x27, 0xfe, 0x79, 0xf2, 0xc3, 0xb8, 0x82, 0x44, 0x92, 0x6f, 0x55,
	0x2f, 0x22, 0xfe, 0x99, 0x68, 0xb7, 0x85, 0xe8, 0x44, 0x24, 0xb1, 0x84, 0x98, 0x17, 0x62, 0x5a,
	0x7d, 0x57, 0xce, 0xb3, 0xea, 0xa7, 0x47, 0xf1, 0x77, 0x4e, 0xf8, 0xb6, 0xfd, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0x10, 0xdc, 0xbe, 0x9e, 0xf6, 0x00, 0x00, 0x00,
}
