// Code generated by protoc-gen-go.
// source: github.com/tomogoma/seedms/server/proto/seed.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	github.com/tomogoma/seedms/server/proto/seed.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto1.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code     int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Greeting string `protobuf:"bytes,3,opt,name=greeting" json:"greeting,omitempty"`
	Detail   string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto1.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HelloResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HelloResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto1.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto1.RegisterType((*HelloResponse)(nil), "proto.HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for Seed service

type SeedClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type seedClient struct {
	c           client.Client
	serviceName string
}

func NewSeedClient(serviceName string, c client.Client) SeedClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &seedClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *seedClient) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Seed.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seed service

type SeedHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterSeedHandler(s server.Server, hdlr SeedHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Seed{hdlr}, opts...))
}

type Seed struct {
	SeedHandler
}

func (h *Seed) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.SeedHandler.Hello(ctx, in, out)
}

func init() {
	proto1.RegisterFile("github.com/tomogoma/seedms/server/proto/seed.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x86, 0xdd, 0x5a, 0x36, 0x3a, 0x51, 0x0f, 0xe3, 0xc6, 0x90, 0x3d, 0x99, 0x9e, 0x3c, 0x95,
	0x64, 0xf5, 0xe0, 0xc1, 0x07, 0xf0, 0x5c, 0x9f, 0xa0, 0xbb, 0x4c, 0x90, 0x58, 0x98, 0x0a, 0xd4,
	0xe7, 0x37, 0x0e, 0x8d, 0xd1, 0x13, 0xff, 0xff, 0xc1, 0x17, 0x66, 0xe0, 0xe0, 0x7c, 0x79, 0x5f,
	0x8e, 0xfd, 0x89, 0x83, 0x29, 0x1c, 0xd8, 0x71, 0x18, 0x4d, 0x26, 0xb2, 0x21, 0x9b, 0x4c, 0xe9,
	0x8b, 0x92, 0x99, 0x13, 0x17, 0x16, 0xd6, 0x4b, 0x44, 0x25, 0x47, 0xf7, 0x0c, 0x57, 0xaf, 0x34,
	0x4d, 0x3c, 0xd0, 0xe7, 0x42, 0xb9, 0xe0, 0x0e, 0x54, 0xe1, 0x0f, 0x8a, 0x7a, 0x73, 0xbf, 0x79,
	0xb8, 0x1c, 0x6a, 0x41, 0x84, 0x36, 0x8e, 0x81, 0x74, 0x23, 0x50, 0x72, 0xe7, 0xe0, 0x7a, 0x35,
	0xf3, 0xcc, 0x31, 0x13, 0xde, 0x40, 0xe3, 0xed, 0xea, 0x35, 0xde, 0xfe, 0x48, 0x27, 0xb6, 0x55,
	0x52, 0x83, 0x64, 0xdc, 0xc3, 0x85, 0x4b, 0x44, 0xc5, 0x47, 0xa7, 0xcf, 0xe5, 0xe5, 0x6f, 0xc7,
	0x3b, 0xd8, 0x5a, 0x2a, 0xa3, 0x9f, 0x74, 0x2b, 0x37, 0x6b, 0x3b, 0xbc, 0x40, 0xfb, 0x46, 0x64,
	0xf1, 0x09, 0x94, 0x7c, 0x88, 0xb7, 0x75, 0x85, 0xfe, 0xef, 0xe0, 0xfb, 0xdd, 0x7f, 0x58, 0x67,
	0xea, 0xce, 0x8e, 0x5b, 0xc1, 0x8f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21, 0x26, 0xdf, 0x79,
	0x24, 0x01, 0x00, 0x00,
}
